.github/pull_request_template.md
CODEOWNERS
README.md
docs/.wordlist.txt
docs/how-to/deploy_the_sdcore_upf.md
docs/how-to/index.md
docs/index.md

- Adds how-to guide to deploy the UPF
- Adds a PR template
- Adds a CODEOWNERS file

Adds how-to guide to deploy the UPF

---

docs/how-to/deploy_sdcore.md
docs/how-to/deploy_the_sdcore_control_plane.md
docs/how-to/index.md
docs/how-to/integrate_sdcore_with_observability.md

Adds how-to guides for deploying the sdcore bundle

Adds how-to guides for deploying the sdcore bundle

---

docs/.wordlist.txt
docs/reference/index.md

Adds information about the bundles that are deployed following the instructions in the "How to" docs.

Improves the "How to" docs.

---

README.md
docs/.wordlist.txt
docs/index.md

Improves project introduction

---

docs/.wordlist.txt
docs/tutorial/index.md

Add hardware requirements to tutorial. The requirements were estimated from running the tutorial locally. The CPU requirements are for the `UPF` container built for recent CPUs.

Add hardware requirements to tutorial

---

docs/tutorial/01_bootstrap_juju.md

Removes unnecessary steps in tutorial

chore: Removes unnecessary steps in tutorial

---

docs/.wordlist.txt
docs/how-to/integrate_sdcore_with_observability.md
docs/tutorial/04_integrate_sdcore_with_observability.md

Adds logs coming from the SD-Core model. Currently this only includes logs coming from MongoDB.

feat: Adds logs coming from the SD-Core model

---

docs/tutorial/03_configure_sdcore.md

Update the tutorial to use the external UPF service

Update tutorial to use upf-external

---

docs/.wordlist.txt
docs/tutorial/04_integrate_sdcore_with_observability.md

Increases the address range for metallb as now the AMF and UPF both require an address.
This is a quick fix to get the tutorial working again. A re-organisation of this metallb information will follow putting it in a different section.

Update metallb range

---

renovate.json

Enables auto-merging of Renovate PRs if minor version of patch was changed.

Enable auto-merging Renovate PRs

---

docs/.wordlist.txt
docs/explanation/index.md
docs/explanation/security.md
docs/index.md

Adds Explanation section with security content. Currently this section contains information about:
- ROCK's
- TLS

[Feat] Adds Explanation section with security content

---

.github/workflows/issues.yaml

Sync issues with Jira

---

docs/explanation/index.md
docs/explanation/observability.md

Adds explanation section about observability

[Feat] Adds explanation section about observability

---

docs/tutorial/02_deploy_sdcore.md
docs/tutorial/04_integrate_sdcore_with_observability.md

Moves the part where we enable MetalLB to the second section where we deploy SD Core, as it is now required there.

Move enabling of MetalLB to the deploy sdcore part of the tutorial

---

docs/how-to/deploy_sdcore.md

Adds a requirement for a `LoadBalancer` K8s Service to the How-to guides.

Add the requirement for a LoadBalancer K8s Service

---

docs/index.md

This fixes the current state of things where the headers in the grid are barely readable in dark mode.
Fixes #135

bugfix: Fixes main navigation grid

---

docs/tutorials/getting_started.md

MicroK8s addon management used to be done in 2 different places in the tutorial. We now combine all MicroK8s related operations in one section to logically separate it from the rest.

docs: Combines all MicroK8s related commands in 1 step

---

docs/how-to/index.md

This PR separates logically the operations that are to be done in SD-Core. The goal is to make it simpler for users to navigate the documentation.

docs: Separates day 1 from day 2 operations

---

docs/how-to/backup_sdcore.md
docs/how-to/restore_sdcore.md
docs/tutorials/getting_started.md

Bumps mongodb version to 6/beta

chore: Bumps mongodb version to 6/beta

---

docs/how-to/deploy_sdcore_cups.md
docs/how-to/deploy_sdcore_gnbsim.md
docs/how-to/deploy_sdcore_standalone.md
docs/how-to/deploy_sdcore_user_plane_with_hugepages.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
- N/A I have added tests that validate the behaviour of the software
- N/A I have bumped the version of the library

feat: TELCO-948 Update to use track 1.3/beta

---

docs/conf.py
docs/index.md

Add matrix room link to meet the community

chore: add matrix room link to meet the community
